
<?php echo $this->render('index/navbar_index.phtml') ?>

<div class="content" xmlns="http://www.w3.org/1999/html">
    <div class="frame cl frame-1" id="frameE47quR">
        <div class="column frame-1-c" id="frameE47quR_left">
            <div class="" style="margin-top: 0px;margin-right: 0px;margin-bottom: 8px;margin-left: 0px;">
                <div class="pane_T">
                    <div class="pane_T_l">
                        <div class="pane_T_r">
                            <div class="pane_T_c">

                            </div>
                        </div>
                    </div>
                </div>

                <div class="pane_C">
                    <div class="pane_C_l">
                        <div class="pane_C_r">
                            <div class="pane_C_c" style="padding-top:0px;padding-right: 0px;padding-bottom: 0px;padding-left: 0px;">
                                <div id="uDWUIw" style="">
                                    <script type="text/javascript" src="/js/myfocus-1.2.0.full.js">

                                    </script>

                                    <div class="mF_expo2010_wrap">
                                        <div id="xwOxUk" style="visibility: hidden;" class=" mF_expo2010 mF_expo2010-xwOxUk">
                                            <ul class="pic">
                                                <li style="display: none; opacity: 0;"><a href="http://www.tibetoutdoors.com/T08GangRenBoQiZhuanShanTuBu/"><img src="/img/tu1~1.jpg" thumb="" alt="马年”冈仁波齐“转山" text=""></a></li>
                                                <li style="display: block; opacity: 1;"><a href="http://www.tibetoutdoors.com/MaKaLuHuWaiChuangShiRen-DaDanZeng/"><img src="/img/tu2~1.jpg" thumb="" alt="08年大小旦增奥运火炬珠峰传递" text="Makalu Outdoor,西藏马卡鲁户外,西藏高原徒步,西藏登山服务,慕士塔格峰价格,高原露营,大峡谷穿越,徒步珠峰东坡,徒步珠峰6500,徒步珠峰ABC,阿里转山,徒步墨脱,"></a></li>
                                                <li style="display: none; opacity: 0;"><a href="http://www.tibetoutdoors.com/HuoDongHuiGu/show/18/"><img src="/img/tu3~1.jpg" thumb="" alt="金秋十月珠峰东坡徒步" text="Makalu Outdoor,西藏马卡鲁户外,西藏高原徒步,西藏登山服务,慕士塔格峰价格,高原露营,大峡谷穿越,徒步珠峰东坡,徒步珠峰6500,徒步珠峰ABC,阿里转山,徒步墨脱,"></a></li>
                                                <li style="display: none; opacity: 0;"><a href="http://www.tibetoutdoors.com/MaKaLuHuWaiChuangShiRen-DaDanZeng/"><img src="/img/tu4~1.jpg" thumb="" alt="西藏马卡鲁户外创始人—大旦增第五次登顶珠峰" text="Makalu Outdoor,西藏马卡鲁户外,西藏高原徒步,西藏登山服务,慕士塔格峰价格,高原露营,大峡谷穿越,徒步珠峰东坡,徒步珠峰6500,徒步珠峰ABC,阿里转山,徒步墨脱,"></a></li>
                                                <li style="display: none; opacity: 0;"><a href="http://www.tibetoutdoors.com/T02ZhuFengDongPoTuBu/"><img src="/img/tu5~1.jpg" thumb="" alt="珠峰东坡徒步" text="Makalu Outdoor,西藏马卡鲁户外,西藏高原徒步,西藏登山服务,慕士塔格峰价格,高原露营,大峡谷穿越,徒步珠峰东坡,徒步珠峰6500,徒步珠峰ABC,阿里转山,徒步墨脱,"></a></li>
                                            </ul>
                                            <ul class="txt-bg">
                                                <li><span></span></li>
                                                <li><span></span></li>
                                                <li><span></span></li>
                                                <li><span></span></li>
                                                <li><span></span></li>
                                            </ul>
                                            <ul class="txt">
                                                <li style="bottom: -36px;">
                                                    <a href="http://www.tibetoutdoors.com/T08GangRenBoQiZhuanShanTuBu/">马年”冈仁波齐“转山</a><p></p><span></span>
                                                </li>
                                                <li style="bottom: 0px;">
                                                    <a href="http://www.tibetoutdoors.com/MaKaLuHuWaiChuangShiRen-DaDanZeng/">08年大小旦增奥运火炬珠峰传递</a><p>Makalu Outdoor,西藏马卡鲁户外,西藏高原徒步,西藏登山服务,慕士塔格峰价格,高原露营,大峡谷穿越,徒步珠峰东坡,徒步珠峰6500,徒步珠峰ABC,阿里转山,徒步墨脱,</p><span></span>
                                                </li>
                                                <li style="bottom: -36px;"><a href="http://www.tibetoutdoors.com/HuoDongHuiGu/show/18/">金秋十月珠峰东坡徒步</a><p>Makalu Outdoor,西藏马卡鲁户外,西藏高原徒步,西藏登山服务,慕士塔格峰价格,高原露营,大峡谷穿越,徒步珠峰东坡,徒步珠峰6500,徒步珠峰ABC,阿里转山,徒步墨脱,</p><span></span>
                                                </li>
                                                <li style="bottom: -36px;"><a href="http://www.tibetoutdoors.com/MaKaLuHuWaiChuangShiRen-DaDanZeng/">西藏马卡鲁户外创始人—大旦增第五次登顶珠峰</a><p>Makalu Outdoor,西藏马卡鲁户外,西藏高原徒步,西藏登山服务,慕士塔格峰价格,高原露营,大峡谷穿越,徒步珠峰东坡,徒步珠峰6500,徒步珠峰ABC,阿里转山,徒步墨脱,</p><span></span>
                                                </li>
                                                <li style="bottom: -36px;"><a href="http://www.tibetoutdoors.com/T02ZhuFengDongPoTuBu/">珠峰东坡徒步</a><p>Makalu Outdoor,西藏马卡鲁户外,西藏高原徒步,西藏登山服务,慕士塔格峰价格,高原露营,大峡谷穿越,徒步珠峰东坡,徒步珠峰6500,徒步珠峰ABC,阿里转山,徒步墨脱,</p><span></span>
                                                </li>
                                            </ul>

                                            <ul class="num">
                                                <li class="">
                                                    <a>1</a>
                                                    <span></span>
                                                </li>
                                                <li class="current">
                                                    <a>2</a>
                                                    <span></span>
                                                </li>
                                                <li class="">
                                                    <a>3</a>
                                                    <span></span>
                                                </li>
                                                <li class="">
                                                    <a>4</a>
                                                    <span></span>
                                                </li>
                                                <li class="">
                                                    <a>5</a>
                                                    <span></span>
                                                </li>
                                            </ul>
                                        </div>
                                    </div>

                                    <script type="text/javascript">
                                        myFocus.set({
                                            id:'xwOxUk',
                                            pattern:'mF_expo2010',
                                            time:4,
                                            trigger:'click',
                                            width:980,
                                            height:300,
                                            txtHeight:'default',
                                            path:'/js/'
                                        });
                                    </script>
                                    <div class="clr"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="pane_M">
                    <div class="pane_M_l">
                        <div class="pane_M_r">
                            <div class="pane_M_c">

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="clr">

        </div>
    </div>
    <div class="clr"></div>

    <div class="main_full">

        <div class="content_new">
            <h3 class="t-h2"><em>最新活动</em><a href="/opinions" class="more">更多…</a></h3>
            <div class="clearfix article-box  idx-tuijian">
                <a href="/article/103424/1.html" class="a-img" target="_blank">
                    <img src="/img/new.jpg">
                </a>
                <div class="article-box-ctt">
                    <h4>
                        <a href="/article/103424/1.html" target="_blank">攀登喜马拉雅山</a>
                    </h4>
                    <div class="box-other">
                        <span class="source-quote">时间</span>
                        <time>2014-12-08 21:51:00</time>
                        <br>
                        <span class="source-quote">领队</span>
                        <time>崔敬杰</time>
                        <br>
                        <span class="source-quote">报名时间</span>
                        <time>2014-12-08 21:51:00</time>
                        <br>
                        <span class="source-quote">活动费用</span>
                        <time>1000 人民币</time>
                    </div>
                    <div class="article-summary">
                        不是说非得牺牲整整一代人。换个姿势，你完全可以成为互联网新生代大浪打下来的幸存者甚至冲浪儿
                    </div>
                </div>
            </div>

            <div class="clearfix article-box  idx-tuijian">
                <a href="/article/103424/1.html" class="a-img" target="_blank">
                    <img src="/img/new.jpg">
                </a>
                <div class="article-box-ctt">
                    <h4>
                        <a href="/article/103424/1.html" target="_blank">攀登喜马拉雅山</a>
                    </h4>
                    <div class="box-other">
                        <span class="source-quote">时间</span>
                        <time>2014-12-08 21:51:00</time>
                        <br>
                        <span class="source-quote">领队</span>
                        <time>崔敬杰</time>
                        <br>
                        <span class="source-quote">报名时间</span>
                        <time>2014-12-08 21:51:00</time>
                        <br>
                        <span class="source-quote">活动费用</span>
                        <time>1000 人民币</time>
                    </div>
                    <div class="article-summary">
                        不是说非得牺牲整整一代人。换个姿势，你完全可以成为互联网新生代大浪打下来的幸存者甚至冲浪儿
                    </div>
                </div>
            </div>

        </div>
        <div class="content_recomm">
            <h3 class="t-h2"><em>精彩活动</em><a href="/opinions" class="more">更多…</a></h3>

        </div>
    </div>
</div>

<br>
<?php echo $this->render('index/footer.phtml') ?>
