<div class="header">
    <div class="logo">
        <a href="/" seed="logo">
            <img src="/img/xueying_small.png" style="width:auto;height:auto;" border="0" alt="">
        </a>
    </div>

    <div class="headmenu">
        <br>
        全国统一咨询电话：(+86) 0891-6363321
        <br>
        <div class="tag_search_min">
            <form id="HnAOsB" method="post" name="search" action="http://www.tibetoutdoors.com/search/" onsubmit="ajaxp(this.id);return false;">
                <input id="tag_search_min_mod" name="bymod" type="hidden" value="">
                <a id="tag_search_min_title" href="javascript:;" class="show_select2" onmouseover="showMenu(this.id)">全部</a>
                <input class="tag_search_min_keyword" id="tag_search_min_keyword" value="请输入关键字" onfocus="deleteSearchKey('tag_search_min_keyword','请输入关键字')" onblur="setSerchKey('tag_search_min_keyword','请输入关键字')" name="q">
                <input class="tag_search_min_input" value="搜索" type="image" src="/img/bg.jpg">
            </form>
        </div>

        <script type="text/javascript">
            function deleteSearchKey(k,v)
            {
                window.location.href="/login";
                var name = document.getElementById(k).value;
                if (name == v)
                    document.getElementById(k).value = "";
            }

            function setSerchKey(k,v)
            {
                var name = document.getElementById(k).value;
                if (name == "")
                    document.getElementById(k).value = v;
            }
        </script>

        <div class="clr"></div>
    </div>
    <div class="clr"></div>
</div>
<ul id="css3menu1" class="topmenu">
    <li class="topfirst">
        <a href="http://www.tibetoutdoors.com/"><span>首页</span></a>
    </li>

    <li class="topmenu">
        <a target="_blank" href="http://www.tibetoutdoors.com/ZhuanTiHuoDong/"><span>专题活动</span></a>
    </li>

    <li class="topmenu">
        <a href="http://www.tibetoutdoors.com/GaoYuanTuBu/"><span>高原徒步</span></a>
    </li>

    <li class="topmenu">
        <a href="http://www.tibetoutdoors.com/DengShanFuWu/"><span>登山服务</span></a>
    </li>

    <li class="topmenu">
        <a href="http://www.tibetoutdoors.com/GaoYuanLuYing/">高原露营</a>
    </li>

    <li class="topmenu">
        <a href="http://www.tibetoutdoors.com/ShenDuLvYou/"><span>深度旅游</span></a>
    </li>

    <li class="topmenu">
        <a href="http://www.tibetoutdoors.com/LuXianDingZhi/">路线定制</a>
    </li>

    <li class="topmenu">
        <a target="_blank" href="http://www.tibetoutdoors.com/HuoDongHuiGu/">活动回顾</a>
    </li>

    <li class="topmenu">
        <a target="_blank" href="http://www.tibetoutdoors.com/GuanYuWoMen/"><span>关于我们</span></a>
    </li>

    <li class="toplast">
        <a target="_blank" href="http://www.tibetoutdoors.com/LianXiWoMen/">联系我们</a>
    </li>

</ul>

<div class="clr"></div>
<div style="margin-bottom: 10px"></div>