
<div class="container">

    <form class="form-signin">
        <h2 class="form-signin-heading">Please sign in</h2>
        <input id="login_email" type="text" class="input-block-level" placeholder="Email address">
        <input id="login_pwd" type="password" class="input-block-level" placeholder="Password">
        <label class="checkbox">
            <input type="checkbox" value="remember-me"> Remember me
        </label>
        <button class="btn btn-large btn-primary" type="button" onclick="javascript:loginClick();" value="登录">Sign in</button>
    </form>

</div> <!-- /container -->
<script defer src="/js/ajax/loginclick.js"></script>
<?php echo $this->render('index/footer.phtml') ?>
