<!doctype html>  
<html>  
    <head>  
        <meta http-equiv="Content-Type" content="text/html;charset=utf-8">

        <title>校园百事通</title>

        <link href="/css/bootstrap.css" rel="stylesheet">
        <link href="/css/bootstrap-responsive.css" rel="stylesheet">

        <link rel="stylesheet" type="text/css" href="/css/index.css" charset="utf-8" />
        <script type=text/javascript>
            var ROOTPATH='/';
            var THEMEFILE='index.php';
            var AYACMS='127.0.0.1';
        </script>

        <script src="/js/jquery-1.7.1.min.js" type="text/javascript"></script>
        <script src="/js/MSClass1.65.js" type="text/javascript"></script>
        <script type="text/javascript" src="/js/editor_config.js"></script>
        <script type="text/javascript" src="/js/editor_all_min.js"></script>
        <link rel="stylesheet" href="/css/ueditor.css"/>
        <link rel="stylesheet" type="text/css" href="/css/part_default.css?CyldJo" />
        <link rel="stylesheet" type="text/css" href="/css/pane_default.css?CyldJo" />
        <link rel="stylesheet" type="text/css" href="/css/tag_default.css?CyldJo" />
        <script type="text/javascript" src="/js/part_default.js?CyldJo"></script>
        <script type="text/javascript" src="/js/tag_default.js?CyldJo"></script>
        <link rel="stylesheet" href="/css/mF_expo2010.css">
        <script type="text/javascript" src="/js/part_default.js?CyldJo"></script>
        <script type="text/javascript" src="/js/tag_default.js?CyldJo"></script>


    </head>
    <body>

    <div class="mainbody">
        <div class="container">
            <?php echo $this -> layout() -> content;?>
        </div>
    </div>

    </body>
</html>