<link href="/css/p_set.css" type="text/css" rel="stylesheet"/>
<link href="/css/common.css" rel="stylesheet">
<link href="/css/p_crop.css" rel="stylesheet">
<link href="/css/jquery.Jcrop.css" rel="stylesheet">

<?php echo $this->render('login/navbar_login.phtml') ?>


<div class="container-fluid container" style="padding-top: 85px">
    <div class="row-fluid">
        <div class="span2" style="padding-top: 30px">
            <!--Sidebar content-->
            <?php echo $this->render('setting/left_side_bar.phtml') ?>
        </div>
        <div class="span10" style="padding-top: 30px">
            <!--Body content-->
            <div class="hero-unit">

                    <!-- rl start -->
                <div class="rl_cont">

                    <!-- rl_box01 start -->
                    <div class="rl_box01" id='pfile'>
                        <h3><span>修改头像</span></h3>
                    </div>
                    <!-- rl_box01 end -->

                    <!-- start -->
                    <div class="rr_box02_cont">

                        <!-- 图片上传 -->
                        <form name="form" action="" method="post" enctype="multipart/form-data">
                            <table cellpadding="0" cellspacing="0" class="tableForm">
                                <tr><th class="gray lh30" style="font-weight:normal!important;">请上传一张图片,支持gif、jpg、jpeg、png格式,文件大小不能超过5MB</th></tr>
                                <tr>

                                    <td><input id="file" type="file" size="36" name="file" class="input ml5" style="height:25px; line-height: 20px" /></td>
                                    <td><button class="buttonUpload btn" id="buttonUpload" onclick="return ajaxFileUpload();">上传图片</button></td>
                                </tr>
                            </table>
                        </form>
                        <!-- end -->

                        <!-- start -->
                        <div class="r_box_pic">
                            <div class="l_pic s_linecolor"><img src="<?php echo $this->site['images'];?>updata_info.gif" width="300" height="300" /></div>
                            <!-- 图片剪切预览区 -->

                            <div class="rightArea" style="line-height: 12px">
                                <div class="line1">
                                    <div class="photo1">

                                        <img src = "<?php if(isset($this->avatararr['big'])) echo $this->avatararr['big'];else echo $this->site['images'].'file_header.jpg';?>"></img>
                                    </div>
                                    <div class="description des1">大尺寸头像，140&nbsp;<span class="multiSymbol">X</span>&nbsp;140像素</div>
                                </div>
                                <div class="line2">
                                    <div class="photo2">
                                        <img src = "<?php if(isset($this->avatararr['middle'])) echo $this->avatararr['middle'];else echo $this->site['images'].'file_header.jpg';?>"></img>
                                    </div>
                                    <div class="description">中尺寸头像<br />50&nbsp;<span class="multiSymbol">X</span>&nbsp;50像素</div>
                                </div>
                                <div class='line3'>
                                    <div class="photo3">
                                        <img src = "<?php if(isset($this->avatararr['small'])) echo $this->avatararr['small'];else echo $this->site['images'].'file_header.jpg';?>"></img>
                                    </div>
                                    <div class="description1">小尺寸头像<br />30&nbsp;<span class="multiSymbol">X</span>&nbsp;30像素</div>
                                </div>
                            </div>
                            <div class="clear"></div>
                            <!-- end -->
                        </div>
                        <!-- end -->
                        <form class="cutForm" id="cutForm" onsubmit="return checkCoords();" style="clear:both;">
                            <input type="hidden" id="x" name="x" />
                            <input type="hidden" id="y" name="y" />
                            <input type="hidden" id="w" name="w" />
                            <input type="hidden" id="h" name="h" />
                            <input type="submit" value="保存" class="btn-primary" style="margin-left:250px;height:22px;"/>
                        </form>



                    </div>
                    <!-- end -->


                </div>
                <!-- rl end -->


            </div>
        </div>
    </div>
</div>
<?php echo $this->render('index/footer.phtml') ?>
<script defer src="/js/p_crop.js"></script>
<script defer src="/js/ajaxfileupload.js"></script>
<script defer src="/js/jquery.Jcrop.js"></script>

